select a.ACTIVITYID,
	   c.CONTACTID,
	   CASE
			WHEN ACTIVITY_TYPE = 'Call' THEN 'CALL'
			ELSE 'TODO'
		END as ACTIVITY_TYPE,
	   a.REGARDING,
	   CAST(CAST(Datediff(s, '1970-01-01', a.STARTTIME) AS BIGINT)*1000 AS varchar)"STARTTIME",
	   CAST(CAST(Datediff(s, '1970-01-01', a.ENDTIME) AS BIGINT)*1000 AS varchar)ENDTIME,
	   a.DURATION,
	   a.DETAILS,
	   c.vid,
	    CAST(CAST(Datediff(s, '1970-01-01', a.CREATEDATE) AS BIGINT)*1000 AS varchar)CREATEDATE
from TBL_ACTIVITY a
			inner join ACTIVITY_TYPE at on a.ACTIVITYTYPEID = at.ACTIVITYTYPEID
			inner join TBL_CONTACT_ACTIVITY ca on ca.ACTIVITYID=a.ACTIVITYID
			inner join MIG_CONTACTS c on ca.CONTACTID = c.CONTACTID
where ACTIVITY_TYPE in ('To-do','Call') and ISDELETED = 0 and a.ACTIVITYID not in  ('6F3BC3E0-C507-4120-9BD0-9B5E0E47CBF6')